name: Bug Report
description: Report a bug
labels: ["bug"]
assignees: ["hasecilu"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I use the X command this happens
      description: Describe the problem and how it impacts user experience, workflow, maintainability or speed of the code. If the problem appears to be a bug with the current functionality, provide as test case or recipe that reproduces the error. Ideally record a macro and attach it.
    validations:
      required: true
  - type: textarea
    id: full_version
    attributes:
      label: FreeCAD version info + FreeGrid WB version
      placeholder: |
        OS: Arch Linux, btw (Hyprland/hyprland/wayland)
        Architecture: x86_64
        Version: 1.1.0dev.36460 +2653 (Git)
        Build type: Release
        Branch: main
        Hash: 440b96eaf3a2a12a9079b3944101a11cb53a25fe
        Python 3.12.7, Qt 6.8.0, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
        Locale: English/United States (en_US)
        Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
        Installed mods:
          * FreeGrid 2.0.1
      description: Please use the About FreeCAD dialog to copy your full version information and paste it here, include the FreeGrid WB version on it.
      render: shell
  - type: dropdown
    id: category
    attributes:
      label: What is the feature affected?
      options:
        - Parametric objects
        - Sketch
        - Icons
        - Translations
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Switch to FreeGrid WB
        2. Click on X command
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
      description: |
        Add links, references, screenshots or anything that will give us more context about the issue you are encountering!
        If there is a discussion about the problem on the forum, provide link(s) here.
        You can upload or copy your macro here to speed up the diagnosis and debugging.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in. To attach a FCStd file, ZIP it first (GitHub won't recognize the extension otherwise).
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
